/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bemap;

/**
 *
 * @author Micha
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    
    public static final int NORMAL = 0;
    public static final int CLOUD = 1;
    
    public Settings() {
        initComponents();
        update();
        
        transparencySlider.setMinimum(1);
        transparencySlider.setMaximum(255);
        transparencySlider.setValue(50);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(realTimeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(realTimeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(realTimeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(realTimeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void update(){
        int usr = BeMapEditor.mainWindow.getUsrIDofConnectedDevice();
        if(usr == -1 ) idField.setText("---");
        else idField.setText(""+usr);
    }
    
    public int getTransparency(){
        return transparencySlider.getValue();
    }
    
    
    
    public String getExportName(){
        return dataExportFilename.getText();
    }
    
    public int getGlobalStyle(){
        if(normalPoints.isSelected()) return NORMAL;
        else if(colorClouds.isSelected()) return CLOUD;
        else return NORMAL;
    }
    
    public void setConfig(int firmwareVersion, int batteryState, 
                       int memoryState, int sleepTime, int trackingTime, int gasInterval, int tempHumInterval,
                       int timeoutFixLost, int preheatTime, int accBounceThr, int accBounceTime,
                       int accInutThr, int accActThr, int accInutTime){
        versionField.setText((double)(firmwareVersion/100.0)+"");
        if(memoryState >= 0 && memoryState <= 100) memoryStateBar.setValue(memoryState);
        if(batteryState >= 0 && batteryState <= 100) batteryStateBar.setValue(batteryState);
        sleepTimeField.setText(sleepTime+"");
        trackingTimeField.setText(trackingTime+"");
        gasIntervalField.setText(gasInterval+"");
        tempIntervalField.setText(tempHumInterval+"");
        fixlostField.setText(timeoutFixLost+"");
        preheatField.setText(preheatTime+"");
        accBounceThrField.setText(accBounceThr+"");
        accBounceTimeField.setText(accBounceTime+"");
        accInutThrField.setText(accInutThr+"");
        accActThrField.setText(accActThr+"");
        accInutTimeField.setText(accInutTime+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        dataExportFilename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        normalPoints = new javax.swing.JRadioButton();
        colorClouds = new javax.swing.JRadioButton();
        transparencySlider = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        memoryStateBar = new javax.swing.JProgressBar();
        batteryStateBar = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        versionField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sleepTimeField = new javax.swing.JTextField();
        gasIntervalField = new javax.swing.JTextField();
        fixlostField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        trackingTimeField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tempIntervalField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        preheatField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        accBounceThrField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        accBounceTimeField = new javax.swing.JTextField();
        accInutThrField = new javax.swing.JTextField();
        accActThrField = new javax.swing.JTextField();
        accInutTimeField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("BeMapEditor Settings");

        jLabel2.setText("User ID:");

        idField.setEditable(false);
        idField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                idFieldMouseEntered(evt);
            }
        });

        dataExportFilename.setText("data");

        jLabel3.setText("Filename for export:");

        jLabel4.setText(".bemap");

        jLabel5.setText("Style for global data:");

        buttonGroup1.add(normalPoints);
        normalPoints.setSelected(true);
        normalPoints.setText("normal points");
        normalPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                normalPointsMouseClicked(evt);
            }
        });
        normalPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalPointsActionPerformed(evt);
            }
        });

        buttonGroup1.add(colorClouds);
        colorClouds.setText("color clouds");
        colorClouds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorCloudsMouseClicked(evt);
            }
        });

        transparencySlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                transparencySliderMouseReleased(evt);
            }
        });

        jLabel6.setText("Memory state");

        jLabel7.setText("Battery state");

        jLabel8.setText("V:");

        versionField.setEditable(false);
        versionField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                versionFieldMouseEntered(evt);
            }
        });
        versionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versionFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Sleep time: ");

        jLabel10.setText("Gas interval:");

        jLabel11.setText("Timeout fixlost: ");

        sleepTimeField.setText("0");
        sleepTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepTimeFieldActionPerformed(evt);
            }
        });

        gasIntervalField.setText("0");
        gasIntervalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasIntervalFieldActionPerformed(evt);
            }
        });

        fixlostField.setText("0");

        jLabel12.setText("Tracking time:");

        trackingTimeField.setText("0");
        trackingTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackingTimeFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Temp interval:");

        tempIntervalField.setText("0");
        tempIntervalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempIntervalFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Preheat time:");

        preheatField.setText("0");
        preheatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preheatFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Acc bounce threshold:");

        accBounceThrField.setText("0");

        jLabel16.setText("Acc bounce time:");

        jLabel17.setText("Acc inut threshold:");

        jLabel18.setText("Acc inut time:");

        jLabel19.setText("Acc act threshold:");

        accBounceTimeField.setText("0");

        accInutThrField.setText("0");

        accActThrField.setText("0");

        accInutTimeField.setText("0");
        accInutTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accInutTimeFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Apply settings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(normalPoints)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colorClouds)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(transparencySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataExportFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(memoryStateBar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(sleepTimeField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12))
                                    .addComponent(batteryStateBar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fixlostField, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(gasIntervalField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tempIntervalField)
                            .addComponent(trackingTimeField)
                            .addComponent(preheatField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accInutTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accActThrField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accInutThrField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accBounceTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accBounceThrField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(versionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataExportFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(normalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transparencySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(colorClouds, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(memoryStateBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(batteryStateBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sleepTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(trackingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(gasIntervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tempIntervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fixlostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(preheatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(accBounceThrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(accBounceTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(accInutThrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(accActThrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(accInutTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idFieldMouseEntered
        update();
    }//GEN-LAST:event_idFieldMouseEntered

    private void normalPointsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalPointsMouseClicked
       BeMapEditor.mainWindow.updateMap();
    }//GEN-LAST:event_normalPointsMouseClicked

    private void colorCloudsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorCloudsMouseClicked
        BeMapEditor.mainWindow.updateMap();
    }//GEN-LAST:event_colorCloudsMouseClicked

    private void transparencySliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transparencySliderMouseReleased
        BeMapEditor.mainWindow.updateMap();
    }//GEN-LAST:event_transparencySliderMouseReleased

    private void normalPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalPointsActionPerformed

    private void versionFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_versionFieldMouseEntered

    private void trackingTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackingTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackingTimeFieldActionPerformed

    private void tempIntervalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempIntervalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempIntervalFieldActionPerformed

    private void preheatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preheatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preheatFieldActionPerformed

    private void sleepTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sleepTimeFieldActionPerformed

    private void gasIntervalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasIntervalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gasIntervalFieldActionPerformed

    private void accInutTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accInutTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accInutTimeFieldActionPerformed

    private void versionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_versionFieldActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accActThrField;
    private javax.swing.JTextField accBounceThrField;
    private javax.swing.JTextField accBounceTimeField;
    private javax.swing.JTextField accInutThrField;
    private javax.swing.JTextField accInutTimeField;
    private javax.swing.JProgressBar batteryStateBar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton colorClouds;
    private javax.swing.JTextField dataExportFilename;
    private javax.swing.JTextField fixlostField;
    private javax.swing.JTextField gasIntervalField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar memoryStateBar;
    private javax.swing.JRadioButton normalPoints;
    private javax.swing.JTextField preheatField;
    private javax.swing.JTextField sleepTimeField;
    private javax.swing.JTextField tempIntervalField;
    private javax.swing.JTextField trackingTimeField;
    private javax.swing.JSlider transparencySlider;
    private javax.swing.JTextField versionField;
    // End of variables declaration//GEN-END:variables

    
}


